added 700 pairs to swe-eng
apertium/apertium-swe-eng pull request #4
Opened 2018-11-21 05:34 UTC by nathanchi

I added 700 pairs to swe-eng.  Verbs were added. 

Output: https://pastebin.com/5F0bVdb5

2018-11-21 05:38 UTC, nathanchi commented
List of Swedish-English words added:
[11:19 swedish-english verbs added.pdf](https://github.com/apertium/apertium-swe-eng/files/2602769/11.19.swedish-english.verbs.added.pdf)

2018-11-22 14:25 UTC, unhammer requested changes
Could you show the output of running the English through too? there's some stuff in there that doesn't seem very verby

2018-11-22 14:25 UTC, unhammer commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>nara</l><r>closely<s n="vblex"/></r></p><par n="vblex_"/></e>
closely is an adverb  (can `nara` mean "move closer to" here? maybe just remove this one)

2018-11-22 14:25 UTC, unhammer commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>saxa</l><r>quote<s n="vblex"/></r></p><par n="vblex_"/></e>
as in "this has been cut-and-pasted from another news paper"? (do we have "citera"?)

2018-11-22 14:25 UTC, unhammer commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>sela</l><r>harness<s n="vblex"/></r></p><par n="vblex_"/></e>
these look like nouns?

2018-11-22 14:25 UTC, unhammer commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>surfa</l><r>sailboard<s n="vblex"/></r></p><par n="vblex_"/></e>
is sailboard a verb?

2018-11-22 19:37 UTC, nathanchi commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>surfa</l><r>sailboard<s n="vblex"/></r></p><par n="vblex_"/></e>
I'll fix these issues.

2018-11-23 08:38 UTC, nathanchi commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>sela</l><r>harness<s n="vblex"/></r></p><par n="vblex_"/></e>
These are all verbs as well as nouns, but I can edit them (or just remove them).

2018-11-23 08:39 UTC, nathanchi commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>surfa</l><r>sailboard<s n="vblex"/></r></p><par n="vblex_"/></e>
To sailboard is a verb, but I can remove it.

2018-11-23 08:41 UTC, nathanchi commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>saxa</l><r>quote<s n="vblex"/></r></p><par n="vblex_"/></e>
The word citera is in the swe-eng bidix.

2018-11-23 09:09 UTC, nathanchi commented
I'm not quite sure what's wrong with the eng-swe direction; when I tried to run an English word to get a Swedish translation, it didn't work.

For example, I ran "angel" through the bidix:
```
NathanChisiMac:apertium-swe-eng nathanchi$ echo "angel" | apertium -d . eng-swe
Warning: Decomposition symbol <:compound:only-L> not found
Warning: Decomposition symbol <:compound:R> not found
```
I got that warning, however, and it didn't work.  

Do you know what the problem might be?

2018-11-23 09:32 UTC, unhammer commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>surfa</l><r>sailboard<s n="vblex"/></r></p><par n="vblex_"/></e>
nah, if it's used it's probably fine; "surf" is in there for the lrx to default to

2018-11-23 09:37 UTC, unhammer commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>sela</l><r>harness<s n="vblex"/></r></p><par n="vblex_"/></e>
IIUC, `sela` is used as as in `att sela på hästen`, putting the harness on the horse[1] – I think I would remove those `sela` translations, unless there's a verb that is used for putting on harnesses (the most common use of "to harness" is so different I think it'd lead to some confusing translations)

[1] "Först ska vi sela på hästen!" says https://lycklighast.wordpress.com/2012/03/01/korning-for-dummies-del-3-hur-gor-man/ which google translates as "first we will *sell* the horse" 😂

2018-11-23 09:41 UTC, unhammer commented
> I'm not quite sure what's wrong with the eng-swe direction; when I tried to run an English word to get a Swedish translation, it didn't work.
> 
> For example, I ran "angel" through the bidix:
> 
> ```
> NathanChisiMac:apertium-swe-eng nathanchi$ echo "angel" | apertium -d . eng-swe
> Warning: Decomposition symbol <:compound:only-L> not found
> Warning: Decomposition symbol <:compound:R> not found
> ```
> 
> I got that warning, however, and it didn't work.
> 
> Do you know what the problem might be?

The `modes.xml` file uses  `lt-proc -e` which turns on compound decomposition (useful for other Germanic languages that don't put spaces in compounds), but it seems the English monodix doesn't include the special symbols that say when compound decomposition should happen, so it just gives a little warning about that. Check the modes file that it uses the right English monodix, and that it only uses `-e` if that dix has sdef's `compound-R` / `compound-only-L`. It should still work though, so something else must be up too.

2018-11-23 19:36 UTC, nathanchi commented
I'm sorry, I'm not quite sure if I understand what you mean.  What should I be checking for here?

2018-11-23 19:37 UTC, nathanchi commented
If it isn't the problem with the right English monodix, and if it's something else, should I be checking for something different?

2018-11-23 19:57 UTC, unhammer commented
So e.g. https://github.com/apertium/apertium-swe-eng/blob/master/modes.xml#L274 includes the `-e` argument (as do the eng-swe-debug modes) but eng.dix doesn't include the compound sdefs. Remove the `-e` argument from the lt-proc eng-swe.automorf.bin (but not swe→eng!) parts of modes.xml to get rid of the warning.

2018-11-23 20:15 UTC, nathanchi commented
Okay, I removed the -e arguments from each mention of eng-swe.automorf.bin in apertium-swe-eng's modes.xml, and it looks like the warning is gone.  The word still isn't analyzed correctly, however.

2018-11-23 20:16 UTC, nathanchi commented
This is what it looks like now:

`NathanChisiMac:apertium-swe-eng-final nathanchi$ echo "angel" | apertium -d . eng-swe
NathanChisiMac:apertium-swe-eng-final nathanchi$ 
`

Do you have any further suggestions?

2018-11-23 20:20 UTC, unhammer commented
What about the debug modes? eng-swe-morph etc. (do `ls modes/eng*` to see all)

2018-11-23 20:28 UTC, nathanchi commented
When I ran `echo angel | apertium -d . eng-swe-morph`:

`NathanChisiMac:apertium-swe-eng-final nathanchi$ echo angel | apertium -d . eng-swe-morph
^angel/angel<n><sg>$^./.<sent>$`

2018-11-23 20:33 UTC, nathanchi commented
There was no warning when I ran the debug mode.

2018-11-23 20:35 UTC, nathanchi commented
Should I test each of these modes (e.g. biltrans, dgen, disam, interchunk, lex, postchunk, pretransfer, tagger, and transfer)?

2018-11-23 20:43 UTC, nathanchi commented
Running `echo angel | apertium -d . eng-swe-postchunk` yielded the same two warnings.

2018-11-23 20:45 UTC, nathanchi commented
Okay, that warning was removed.  Do you have any other suggestions?

2018-11-23 20:47 UTC, nathanchi commented
Running `disam` gave this:

apertium-swe-eng-final nathanchi$ echo angel | apertium -d . eng-swe-disam
"<angel>"
	"angel" n sg
"<.>"
	"." sent

The other debug modes (besides morph) didn't yield anything, though.

2018-11-23 20:55 UTC, nathanchi commented on apertium-swe-eng.swe-eng.dix
> +      <e><p><l>sela</l><r>harness<s n="vblex"/></r></p><par n="vblex_"/></e>
Maybe `to yoke` would be more appropriate than `to harness`.  That's more unambiguous.

2018-11-23 21:08 UTC, unhammer commented
tried it on my machine, it seems apertium-tagger is going at 100%, presumably missing an `-x` argument

2018-11-23 21:12 UTC, unhammer commented
merge master and try again :)

2018-11-23 23:01 UTC, nathanchi commented
Okay, I cloned the updated swe-eng bidix to see whether it would work and ran "angel" through it again.
It still doesn't work, though.  Is there something more I should fix?
`NathanChisiMac:apertium-swe-eng nathanchi$ echo "angel" | apertium -d . eng-swe
`

2018-11-23 23:04 UTC, nathanchi commented
swe-eng still works, though, but eng-swe doesn't work.

2018-11-23 23:11 UTC, nathanchi commented
Actually, it works now!  :)

2018-11-24 00:04 UTC, nathanchi commented
New PR: https://github.com/apertium/apertium-swe-eng/pull/5

2018-11-24 09:31 UTC, nathanchi commented
Okay, thanks for merging the PR!  This corresponds to the GCI task https://codein.withgoogle.com/dashboard/task-instances/6458867622871040/.  When you have time, could you approve it, please?

2018-11-24 19:26 UTC, closed without merging